spring:
  application:
    name: tarefa

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_login
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8085

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key